### ISSUE TITLE
It does not work with models with custom layers.

### ISSUE THREAD

**Issue by davidjones1** [keisen/tf-keras-vis#90] opened 2022-06-14 23:56 UTC
@keisen, Good library and clean code. Thanks

I have a very simple model for testing a custom convolutional layer. 
Your code does not work for all the visualizations.
Two main errors:
1- it needs to have a model to be cloned. It can be easily fixed by overriding get_config. (Somehow)
2- But the second error is quite a big issue. None of the visualization works for a model with custom layers.
![image](https://user-images.githubusercontent.com/13497197/173708134-094230bf-94f8-4d5b-913f-1a5482133552.png)

I could make the conv layers visualization work (and also dense) but the rest: no success.
Does you code work only with pre-trained models?

**Comment by keisen** [comment] 2022-11-08 03:53
Hi, @davidjones1 . 

> Does you code work only with pre-trained models?

No, it also works for custom models.
Could you submit your code and the **full stack** of the error message?

**Comment by davidjones1** [comment] 2022-11-20 16:51
IT does not work unfortunately. I would not share the code with you due to intellectual property.

    On Monday, November 7, 2022 at 10:53:16 PM EST, Yasuhiro Kubota ***@***.***> wrote:  
 
 


Hi, @davidjones1 .


Does you code work only with pre-trained models?


No, it also works for custom models.
Could you submit your code and the full stack of the error message?

**Comment by keisen** [comment] 2022-11-22 03:37
Hi, @davidjones1 . 

I'm going to close this issue because there is no cue enough to understand it for now.
Please feel free to reopen if you get the code to reproduce the error or face it again on shareable code.

Thanks!

**Closed by keisen** 2022-11-22 03:37 UTC
